default rel

global HashTable_find_value

section .text

HashTable_find_value:  ; Code below was generated by clang compiler.
        mov     rcx, -1085102592571150095
        mov     rax, rsi
        mul     rcx
        mov     rax, qword [rdi + 8]
        shr     rdx, 4
        mov     rcx, rdx
        shl     rcx, 4
        add     rcx, rdx
        sub     rsi, rcx
        lea     rdx, [rsi + 4*rsi]
        mov     rcx, qword [rax + 8*rdx + 16]
        test    rcx, rcx
        je      .LBB0_4
        mov     rax, qword [rax + 8*rdx]
        add     rax, 32
.LBB0_2:                                ; %for.body
        vmovdqa ymm1, yword [rax]
        vptest  ymm1, ymm0
        jb      .LBB0_5
        add     rax, 64
        add     rcx, -1
        jne     .LBB0_2
.LBB0_4:
        xor     eax, eax
.LBB0_5:                                ; %cleanup3
        vzeroupper
        ret
